advices_list = {
    "Enerji tasarruflu ampuller kullanın": "Enerji tasarruflu ampuller, geleneksel ampullere göre daha az enerji tüketir ve daha uzun ömürlüdür.",
    "Elektrikli cihazları kullanım sonrası tamamen kapatın": "Bekleme modundaki cihazlar bile enerji tüketir, bu yüzden fişten çekmek önemlidir.",
    "Duvar yalıtımı yaparak evinizi enerji verimli hale getirin": "Yalıtım, evinizdeki ısı kaybını önler ve enerji tasarrufu sağlar.",
    "Güneş panelleri kurmayı düşünün": "Kendi enerjinizi üretmek, karbon ayak izinizi azaltır.",
    "Enerji tasarruflu cihazlar satın alın": "Daha az enerji tüketen cihazlar, çevreye zararınızı azaltır.",
    "Toplu taşıma araçlarını tercih edin": "30 kişinin bir otobüsle seyahat etmesi, 30 ayrı aracın yaratacağı kirliliği önler.",
    "Daha sık yürüyün veya bisiklet kullanın": "Fosil yakıt kullanımını azaltır ve sağlığınız için faydalıdır.",
    "Araba paylaşımı yapın (carpool)": "Aynı rota üzerindeki bireylerin araç paylaşımı yapması emisyonları azaltır.",
    "Elektrikli veya hibrit araç satın almayı düşünün": "Bu araçlar, fosil yakıt tüketimine daha az bağımlıdır ve daha az emisyon üretir.",
    "Uçuşlarınızı sınırlayın ve mümkünse trenle seyahat edin": "Havacılık sektörü büyük karbon salınımlarına yol açar, tren daha çevreci bir seçenektir.",
    "Suyu idareli kullanın (örneğin duş süresini kısaltın)": "Daha az su kullanarak enerji tüketimini ve su kaynakları üzerindeki baskıyı azaltırsınız.",
    "Su tasarruflu musluk başlıkları kullanın": "Bu başlıklar, su akışını azaltarak kaynak tasarrufu sağlar.",
    "Sızdıran muslukları hemen tamir edin": "Bir musluk saniyede bir damla sızdırırsa yılda yüzlerce litre su kaybına yol açabilir.",
    "Yağmur suyu toplayarak yeniden değerlendirin": "Bahçe sulama veya temizlikte kullanılabilir, böylece su israfını önlersiniz.",
    "Bahçenizi az su isteyen bitkilerle tasarlayın": "Kuraklığa dayanıklı bitkiler su tüketimini azaltır.",
    "Geri dönüşüm yapın": "Atıkların yeniden işlenmesi, doğal kaynakların korunmasına yardımcı olur.",
    "Organik atıkları kompostlayın": "Kompost, atıkları besleyici toprağa dönüştürerek doğal döngüye katkı sağlar.",
    "Plastik kullanımını azaltın (örneğin, bez çanta kullanın)": "Plastikler çevrede uzun yıllar kalır, alternatifler kullanarak bu etkiden kaçınırsınız.",
    "Tek kullanımlık ürünlerden kaçının": "Tekrar kullanılabilir ürünler, atık miktarını önemli ölçüde azaltır.",
    "Yerel ve mevsimlik ürünleri tercih edin": "Uzak mesafelerden taşınan ürünler daha fazla emisyon üretir.",
    "Bitki bazlı beslenmeyi artırın": "Hayvansal ürünlerin üretimi daha fazla sera gazı salınımına neden olur.",
    "Fazla yemek israfından kaçının": "Yemek israfını azaltmak, hem kaynak tasarrufu sağlar hem de çevreye katkı yapar.",
    "Organik ürünler seçin": "Organik tarım, daha az kimyasal kullanır ve toprak sağlığını korur.",
    "Ambalajsız ürünleri satın almaya özen gösterin": "Ambalaj üretimi, kaynak ve enerji tüketimine neden olur.",
    "Ağaç dikimi projelerine katılın": "Ağaçlar karbonu hapseder ve havayı temizler.",
    "Biyoçeşitliliği koruyan ürünler kullanın": "Biyoçeşitlilik, ekosistemlerin sağlıklı işleyişini destekler.",
    "Çevresel projelere gönüllü olarak destek verin": "Gönüllü katılım, çevresel farkındalığı artırır.",
    "Yerel parkları ve doğal alanları koruyun": "Yeşil alanlar, karbon emilimini artırır ve yaşam alanlarını korur.",
    "Arıcılığı destekleyin (örneğin, arı dostu bitkiler yetiştirin)": "Arılar, ekosistemlerde tozlaşma için kritik öneme sahiptir.",
    "Sürdürülebilir moda markalarını destekleyin": "Sürdürülebilir markalar, daha az kaynak tüketir ve çevreye daha az zarar verir.",
    "İhtiyacınızdan fazla alışveriş yapmayın": "Daha az tüketmek, kaynak tasarrufunu destekler.",
    "İkinci el veya geri dönüştürülmüş ürünler alın": "Yeni üretim gereksinimlerini azaltır ve atık miktarını düşürür.",
    "Kıyafetlerinizi uzun ömürlü tutmaya özen gösterin": "Kıyafetlerinizi tamir ederek daha az tüketim yapabilirsiniz.",
    "Sentetik ve çevreye zarar veren materyallerden kaçının": "Doğal materyaller çevreye daha az zarar verir.",
    "İklim değişikliğiyle ilgili kitaplar okuyun": "Bilgi sahibi olmak, daha bilinçli kararlar almanıza yardımcı olur.",
    "Çocuklara çevre bilinci aşılayın": "Gelecek nesilleri çevreyi koruma konusunda eğitmek önemlidir.",
    "Yerel çevre gruplarına katılın": "Birlikte hareket etmek, daha büyük bir etki yaratır.",
    "Daha sürdürülebilir bir yaşam hakkında bilgi paylaşın": "Bilgi paylaşımı, çevresel farkındalığı artırır.",
    "Doğa belgeselleri izleyerek farkındalık oluşturun": "Doğanın güzelliğini görmek, koruma isteğini artırır.",
    "Gereksiz kağıt kullanımını azaltın": "Dijital alternatife geçmek, ağaç kesimini azaltır.",
    "E-posta yoluyla iletişimi tercih edin": "Fiziksel yazışmalardan daha az kaynak tüketir.",
    "Online faturalandırmayı seçin": "Kağıt tüketimini azaltır ve daha pratiktir.",
    "Gölgelendirme ile evinizde klima kullanımını azaltın": "Doğal yöntemlerle enerji tüketimini azaltabilirsiniz.",
    "Kapı altlarını ve pencere kenarlarını izole edin": "Isı kaybını önleyerek enerji tasarrufu sağlar.",
    "Tam yükte çamaşır ve bulaşık yıkayın": "Daha az su ve enerji tüketerek kaynak tasarrufu yaparsınız.",
    "Yenilenebilir enerji kullanmayı düşünün": "Rüzgar veya güneş enerjisi gibi kaynaklar karbon salınımını azaltır.",
    "Daha kısa programlar kullanan çamaşır makineleri seçin": "Kısa yıkama süreleri daha az enerji ve su tüketir.",
    "Evde bitki bazlı tarifler deneyin": "Bitki bazlı yemekler çevresel etkileri azaltır.",
    "Yerel çiftçilerden alışveriş yapın": "Yerel ürünler nakliyeden kaynaklanan karbon ayak izini azaltır.",
    "Deniz ve plaj temizleme etkinliklerine katılın": "Denizlerdeki kirliliği azaltmak, ekosistemlerin sağlığı için önemlidir.",
    "Kendi doğal gübrelerinizi oluşturun": "Organik atıkları değerlendirerek kimyasal gübre kullanımını azaltabilirsiniz.",
    "Uzun süre dayanıklı ve tamir edilebilir eşyalar satın alın": "Kaliteli ürünler, atık oluşumunu azaltır.",
    "Bahçenizi organik yöntemlerle gübreleyin": "Kimyasal gübrelerin çevreye zararını önlersiniz.",
    "Evde su tasarrufu cihazları kullanın": "Musluk aeratörleri su tüketimini azaltır.",
    "Kendi alışveriş çantanızı getirin": "Plastik torbaların kullanımını önlersiniz.",
    "Karton veya cam ambalajları tercih edin": "Plastiğe kıyasla geri dönüşümü daha kolaydır.",
    "Yüksek enerji verimliliğine sahip beyaz eşyalar kullanın": "Daha az enerji tüketerek çevreyi korur.",
    "Klimayı daha düşük ayarlarda kullanın": "Enerji tasarrufu sağlar ve karbon emisyonlarını azaltır.",
    "Küçük cihazları şarjdan çıkarın": "Tam dolu cihazlar enerji tüketmeye devam eder.",
    "Kağıt havlu yerine kumaş bez kullanın": "Tek kullanımlık ürünlerin çevreye etkisini azaltır.",
    "Kendi sebze ve meyvelerinizi yetiştirin": "Yerel üretim, taşıma kaynaklı emisyonları önler.",
    "Bisikletle işe gitmeyi deneyin": "Hem sağlıklı hem de çevre dostu bir ulaşım yöntemidir.",
    "Evinizde gereksiz ışıkları kapatın": "Basit bir alışkanlıkla enerji tasarrufu yapabilirsiniz.",
    "Eşya alırken ikinci el seçenekleri değerlendirin": "Yeni ürün üretimini azaltır ve kaynak tasarrufu sağlar.",
    "Yerel çevre temizleme kampanyalarına katılın": "Toplumsal farkındalık oluşturur ve çevreyi temiz tutar.",
    "Açık hava sporlarını tercih edin": "Kapalı alanların enerji tüketimini azaltır.",
    "Daha az uçak seyahati yapın": "Havacılık sektörü büyük karbon salınımına yol açar.",
    "Paylaşımlı araç uygulamalarını kullanın": "Bireysel araç kullanımını azaltır.",
    "Evde fazla ısınmadan kaçının": "Daha düşük sıcaklık ayarları enerji tasarrufu sağlar.",
    "Sürdürülebilir turizmi destekleyin": "Çevreye duyarlı tatil planları yaparak doğayı koruyabilirsiniz.",
    "Hayvan dostu tarım ürünlerini tercih edin": "Hayvan refahını ve sürdürülebilirliği desteklersiniz.",
    "Daha az kağıt kullanarak dijital notlar alın": "Kağıt tüketimini ve ağaç kesimini azaltır.",
    "Eski cihazlarınızı bağışlayın veya geri dönüştürün": "Atık oluşumunu önler ve geri dönüşüm döngüsüne katkı sağlar.",
    "Gölgeleme veya panjur kullanarak güneş ısısını kontrol edin": "Enerji tüketimini azaltır.",
    "Su tasarrufu sağlamak için damlama sulama sistemi kurun": "Bahçe sulamasında suyun israfını önler.",
    "Daha fazla ağaçlandırma etkinliklerine katılın": "Doğal alanların korunmasını destekler.",
    "Evde doğal temizlik malzemeleri kullanın": "Kimyasal atıkları ve zararlı etkileri önler.",
    "Kendi bardak veya mataralarınızı yanınızda taşıyın": "Tek kullanımlık ürünlere olan ihtiyacı azaltır.",
    "Daha fazla toplu taşımayı destekleyin": "Şehirlerdeki emisyonların azalmasını sağlar.",
    "Ekolojik ayak izinizi ölçen uygulamalar kullanın": "Kendi tüketim alışkanlıklarınızı analiz ederek iyileştirme yapabilirsiniz.",
    "Yerel çevre politikalarına destek verin": "Toplumun çevre dostu kararlar almasını teşvik eder.",
    "Su akışını kontrol eden cihazlar kurun": "Musluk ve duşlarda gereksiz su tüketimini önler.",
    "Karbon ofset projelerine bağış yapın": "Kendi karbon salınımınızı dengeleyebilirsiniz.",
    "Doğal enerji kaynaklarını araştırın": "Güneş, rüzgar veya jeotermal gibi yenilenebilir enerji türlerini öğrenebilirsiniz.",
    "Uzun ömürlü akıllı ampuller kullanın": "Enerji tasarrufunu artırır ve maliyetleri azaltır.",
    "Güneş ışığını maksimum kullanarak aydınlatmayı azaltın": "Doğal ışık kaynaklarını etkin kullanabilirsiniz.",
    "Arı dostu çiçek ve bitkiler yetiştirin": "Biyoçeşitliliğin korunmasına katkı sağlar.",
    "Daha küçük çaplı çamaşır ve bulaşık yıkama makineleri tercih edin": "Küçük cihazlar daha az enerji ve su tüketir.",
    "Yerel bal üreticilerini destekleyin": "Yerel ekonomiye katkı sağlar ve arıcılığın devamını destekler.",
    "Kendi alışveriş listenizi planlayarak gereksiz satın alımlardan kaçının": "İsrafı ve fazla tüketimi önlersiniz.",
    "Mevsimsel enerji tasarrufu çözümleri uygulayın": "Yaz ve kış aylarında enerji tüketiminizi optimize edebilirsiniz.",
    "Çevre dostu tatil konaklamalarını tercih edin": "Sürdürülebilir turizm uygulamalarını destekler.",
    "Çöp azaltma hedefleri belirleyin": "Kendi günlük atık üretiminizi izleyerek azaltabilirsiniz."
}